### ISSUE TITLE
Internal client error. No creators were authorized during login

### ISSUE THREAD

**Issue by Lumanyii** [Roblox/roblox-blender-plugin#45]
No idea why this is happening, it starts doing this every time I try to log back into ROBLOX,

Tried reinstalling it but it failed to fix the problem but here's the console.

Traceback (most recent call last):
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\roblox-blender-plugin\lib\oauth2_login_operators.py", line 69, in on_login_complete
    task.result()
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\roblox-blender-plugin\lib\oauth2_client.py", line 192, in login
    raise LoginError from handler.request_handled_event.exception
roblox-blender-plugin.lib.oauth2_client.LoginError

**Comment by Nightriff** [comment]
This happens if you go through the process of logging in with Roblox without selecting/authorizing any "creators" during login. You should select at least either your own account as an authorized creator or a group you have permissions to upload to.
