### ISSUE TITLE
Dependency installation fails - Non-zero exit status 3221225781

### ISSUE THREAD

**Issue by Faxel3X** [Roblox/roblox-blender-plugin#8]
I downloaded it from code as zip and made it a addon then i got this whats in the image
![Screenshot 2023-08-24 201145](https://github.com/Roblox/roblox-blender-plugin/assets/143144043/5bd022ac-57b2-4cca-a5d2-e612f70166ae)

**Comment by itsFrank** [comment]
This is a silly question, but did you click the button?

The plugin has a few dependencies that need to be installed. Note you may also be on an older version of blender that isn't compatible with the plugin. Though the install step should let you know if you are.

**Comment by Faxel3X** [comment]
I clicked the button but seemed like it did nothing

**Comment by Faxel3X** [comment]
Will ummm how long is it to install and I did get something new like a black pop up

**Comment by itsFrank** [comment]
Interesting, it should work on both 3.5 and 3.6, are you able to view the logs from the system console? On windows use ` Window > Toggle System Console`

**Comment by Faxel3X** [comment]
Heres what I got when I clicked Install Dependencies


Traceback (most recent call last):
  File "C:\Users\redfo\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\roblox-blender-plugin-main\lib\install_dependencies.py", line 77, in install_dependencies
    subprocess.run([sys.executable, "-m", "pip", "--version"], check=True)
  File "C:\Program Files\Blender Foundation\Blender 3.2\3.2\python\lib\subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['C:\\Program Files\\Blender Foundation\\Blender 3.2\\3.2\\python\\bin\\python.EXE', '-m', 'pip', '--version']' returned non-zero exit status 3221225781.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\redfo\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\roblox-blender-plugin-main\lib\install_dependencies.py", line 62, in on_install_finished
    task.result()
  File "C:\Users\redfo\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\roblox-blender-plugin-main\lib\install_dependencies.py", line 79, in install_dependencies
    ensurepip.bootstrap()
  File "C:\Program Files\Blender Foundation\Blender 3.2\3.2\python\lib\ensurepip\__init__.py", line 126, in bootstrap
    _bootstrap(root=root, upgrade=upgrade, user=user,
  File "C:\Program Files\Blender Foundation\Blender 3.2\3.2\python\lib\ensurepip\__init__.py", line 193, in _bootstrap
    return _run_pip([*args, *_PACKAGE_NAMES], additional_paths)
  File "C:\Program Files\Blender Foundation\Blender 3.2\3.2\python\lib\ensurepip\__init__.py", line 93, in _run_pip
    return subprocess.run([sys.executable, '-W', 'ignore::DeprecationWarning',
  File "C:\Program Files\Blender Foundation\Blender 3.2\3.2\python\lib\subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['C:\\Program Files\\Blender Foundation\\Blender 3.2\\3.2\\python\\bin\\python.EXE', '-W', 'ignore::DeprecationWarning', '-c', '\nimport runpy\nimport sys\nsys.path = [\'C:\\\\Users\\\\redfo\\\\AppData\\\\Local\\\\Temp\\\\tmpd6e33rib\\\\setuptools-58.1.0-py3-none-any.whl\', \'C:\\\\Users\\\\redfo\\\\AppData\\\\Local\\\\Temp\\\\tmpd6e33rib\\\\pip-21.2.4-py3-none-any.whl\'] + sys.path\nsys.argv[1:] = [\'install\', \'--no-cache-dir\', \'--no-index\', \'--find-links\', \'C:\\\\Users\\\\redfo\\\\AppData\\\\Local\\\\Temp\\\\tmpd6e33rib\', \'setuptools\', \'pip\']\nrunpy.run_module("pip", run_name="__main__", alter_sys=True)\n']' returned non-zero exit status 3221225781.

**Comment by Nightriff** [comment]
Can you try these troubleshooting steps 1 at a time to see if any of them resolve your the issue?
* Run Blender as administrator
* Re-install Blender (you can stick with latest `3.6.2` at the time of writing; `3.2` is the minimum required version, but not the only required version)

If neither of those work, I found some answers around the web indicating this exit status is related to a missing dependency. A bit of a shot in the dark, but maybe try manually installing Microsoft Visual C++ Redistributable. You can find the links for this here: 
https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170#visual-studio-2015-2017-2019-and-2022
You'll probably want [the X64 version](https://aka.ms/vs/17/release/vc_redist.x64.exe).

My hypothesis is it might use this to compile the cryptography library used for decrypting oauth2 keys.

**Comment by Nightriff** [comment]
Closing due to inactivity. Please comment if you are still experiencing this issue or have other relevant information to add to the conversation.
